### ISSUE TITLE
信息项为啥不区分大小写

### ISSUE THREAD

**Issue by icezhaoL** [HongLuDianXue/BaiLu-SED-Tool#1]
生成的结果里面 信息项为啥不区分大小写

**Comment by HongLuDianXue** [comment]
您好，这个是去重算法的问题。临时的解决方式：在生成字典前，取消勾选“结果去重”，然后使用sublime之类的软件去重。后续有时间我会想办法解决该问题，非常感谢您的反馈。

**Comment by HongLuDianXue** [comment]
您好，已在更新的v1.1版本中修复了该问题。
