### ISSUE TITLE
使用B2.txt和C2.txt组合生成字典出现空格分离

### ISSUE THREAD

**Issue by theLSA** [HongLuDianXue/BaiLu-SED-Tool#2]
使用B2.txt和C2.txt组合生成字典出现空格分离（勾选结果去重），如下图：
![bailu-sed-tool-issus00](https://user-images.githubusercontent.com/28248956/70535059-4d5a5a00-1b97-11ea-84b4-4cdfe5ae0494.png)
其他字典组合未测试。

**Comment by HongLuDianXue** [comment]
你好，我在本地测试时没有复现出这个Bug。请问是否是字典缘故导致的？默认的“B2.txt”字典第一行是“空格”字符。

**Comment by theLSA** [comment]
噢应该就是那个空格导致的.....
建议去掉字典的空格吧不然会生成很多无用数据......
